let phrases = [
	"make yourself at home",
	"welcome",
	"awroooo",
	"nice to see you",
	"oh, hi",
	"wolves and watermelon",
	"whuh",
	"the void room",
	"tadaa",
	"check your toffee",
	"try out cornsilog",
	"heyooo",
	"what's up",
	"ayo",
	"who am i",
	"lets hecking gooo",
	"wolf or robot",
	"where am i now",
	"press alt f4",
	"press f5",
	"when you're ready, click the games button",
	"oh my goodness gracious",
	"gg jenshin",
	"non fungible personality",
	"glacier dog",
	"you left your house unanchored",
	"mmmm thanks for your cpu cycles",
	"battery low",
	"there was never a chat",
	"red pandas are yeah",
	"dragons my beloved",
	"cat go meoww",
	"what does the fox say",
	"who dares enter my fine establishment",
	"wear a mask",
	"please get vaccinated",
];
let phrase = phrases[Math.floor(Math.random() * phrases.length)];
document.getElementById("splash").innerHTML = phrase + "<br>";