let phrases = [
	"make yourself at home",
	"welcome",
	"awroooo",
	"nice to see you",
	"oh, hi",
	"wolves and watermelon",
	"whuh",
	"the void room",
	"tadaa",
	"check your toffee",
	"try out cornsilog",
	"heyooo",
	"what's up",
	"ayo",
	"who am i",
	"lets hecking go",
	"wolf or robot",
	"where am i now",
	"press alt f4",
	"press f5",
	"click games please",
	"goodness me",
	"gg jenshin",
	"non fungible personality",
	"glacier dog",
	"you left your house unanchored",
	"mmmm thx for the cpu cycles",
	"battery low",
	"there was never a chat",
	"wear a mask",
	"please get vaccinated",
];
let phrase = phrases[Math.floor(Math.random() * phrases.length)];
document.getElementById("splash").innerHTML = phrase + "<br>";